name: frontend
type: "php:5.6"
build:
    flavor: "symfony"
web:
  document_root: "/dist"
  passthru: "/index.html"
  index_files:
    - "index.html"
  whitelist:
    - "\\.html?$"
    - "\\.css$"
    - "\\.js$"
    - "\\.json$"
    - \.ttf$
    - \.eot$
    - \.woff$
    - \.otf$
    - \.svg$
    - \.ico$
    - \.png$
disk: 2048
hooks:
  build: |
    npm --version
    npm install --production
    bower install -p
    grunt build
  deploy: |
    grunt clear-cache
dependencies:
  ruby:
    sass: "3.4.7"
  nodejs:
      grunt-cli: "~0.1.13"
      bower: "~1.3.3"
