name: frontend
type: nodejs:4.2

web:
  commands:
    start: "npm start"
  locations:
    "/dist":
      passthru: false
      root: "dist"
      allow: true
      rules:
        '\.png$':
          allow: true
          expires: -1
        '\.svg$':
          allow: true
          expires: -1
disk: 1048
hooks:
  build: |
    set -e
    npm --version
    npm install --production
    bower install -p
    grunt build
  deploy: |
    grunt clear-cache
    node server.js
dependencies:
  ruby:
    sass: "3.4.7"
  nodejs:
      grunt-cli: "~0.1.13"
      bower: "~1.3.3"
