version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.0-browsers
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - composer-{{ checksum "composer.json" }}
            - composer-
      - run: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
            - ~/.composer/cache
          key: composer-{{ checksum "composer.json" }}
  deploy:
    docker:
      - image: williamyeh/ansible:ubuntu16.04
    steps:
      - checkout
      - run: ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i "${DEPLOY_SERVER}," -u ${DEPLOY_USER} .circleci/playbook.yml

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: nextgen
