version: 2

install_prestissimo: &install_prestissimo
  name: Hirak
  command: composer global require "hirak/prestissimo:^0.3"
restore_cache: &restore_cache
  keys:
    - composer-{{ checksum "composer.json" }}
    - yarn-{{ checksum "tests/yarn.lock" }}
save_composer_cache: &save_composer_cache
  paths:
    - ./vendor
    - ~/.composer/cache
  key: composer-{{ checksum "composer.json" }}
save_yarn_cache: &save_yarn_cache
  paths:
    - ~/.cache/yarn
  key: yarn-{{ checksum "tests/yarn.lock" }}

jobs:
  build:
    docker:
      - image: mglaman/ci-images:circleci-php7.2-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo apt update && sudo apt-get install -y sqlite3
      - restore_cache: *restore_cache
      - run: *install_prestissimo
      - run: composer install -n --prefer-dist
      - save_cache: *save_composer_cache
      - run:
          name: Disable xdebug
          command: |
            sudo sed -i 's/^zend_extension/;zend_extension/g' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - run:
          name: Start server
          command: ./bin/robo run:server
          background: true
      - run:
          name: Setup
          command: |
            ./bin/robo setup
            ./bin/robo drush:cr
      - run:
          name: Install test dependencies
          command: |
            cd tests
            yarn install
      - save_cache: *save_yarn_cache
      - run:
          name: Test the code
          command: |
            cd tests
            ./node_modules/.bin/nightwatch
      - store_test_results:
          path: tests/tests_output
      - store_artifacts:
          path: tests/screenshots
  deploy:
    docker:
      - image: williamyeh/ansible:ubuntu16.04
    steps:
      - checkout
      - run: ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i "${DEPLOY_SERVER}," -u ${DEPLOY_USER} .circleci/playbook.yml

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
