---
- hosts: all
  become: no
  tasks:
    - name: Check out Drupal to the docroot.
      git:
        repo: "git@github.com:mglaman/contribkanban.com.git"
        version: "nextgen"
        update: true
        force: yes
        dest: "/var/www/contribkanban.com"
        accept_hostkey: true
      register: deploy_repo_updated
      become: no

    - name: Run composer install.
      composer:
        command: install
        working_dir: "/var/www/contribkanban.com"
      become: no

    - name: Define deploy_updated
      set_fact:
        deploy_updated: "{{ deploy_repo_updated.changed|default(true) }}"

    - name: Run the deploy script.
      command: "/var/www/contribkanban.com/bin/robo deploy --load-from /var/www/contribkanban.com"
      when: deploy_updated
